CREATE TABLE `your-project.weather_dataset.weather_data` (
  time INT64 NOT NULL,
  altimeter_setting FLOAT64,
  cloud_base FLOAT64,
  cloud_ceiling FLOAT64,
  cloud_cover INT64,
  dew_point FLOAT64,
  evapotranspiration FLOAT64,
  freezing_rain_intensity FLOAT64,
  humidity INT64,
  ice_accumulation FLOAT64,
  ice_accumulation_lwe FLOAT64,
  precipitation_probability FLOAT64,
  pressure_sea_level FLOAT64,
  pressure_surface_level FLOAT64,
  rain_accumulation FLOAT64,
  rain_intensity FLOAT64,
  sleet_accumulation FLOAT64,
  sleet_accumulation_lwe FLOAT64,
  sleet_intensity FLOAT64,
  snow_accumulation FLOAT64,
  snow_accumulation_lwe FLOAT64,
  snow_depth FLOAT64,
  snow_intensity FLOAT64,
  temperature FLOAT64,
  temperature_apparent FLOAT64,
  uv_health_concern FLOAT64,
  uv_index FLOAT64,
  visibility FLOAT64,
  weather_code INT64,
  wind_direction FLOAT64,
  wind_gust FLOAT64,
  wind_speed FLOAT64,
  city STRING,
  county STRING,
  state STRING,
  postal_code STRING,
  country STRING,
  lat FLOAT64,
  lon FLOAT64
)
PARTITION BY DATE(TIMESTAMP_SECONDS(time))
CLUSTER BY city, state;